### PR TITLE
Spike vexflow

### PR DESCRIPTION
**Pull request by caiokf**
I did some spikes with VexFlow and so far I was able to:

- [x] bypass validation of the rendered notation (https://jsfiddle.net/gs4v6k6d/153/), so we can add notes without restrictions, 

- [x] able to start creating layers of notes (for questions, answers, etc)

- [x] add ghost notes for spacing

- [x] add some basic hover/interactivity. This basic interactivity leads me to believe that it should be easy to do more complex things, since I can control the classes/html of the generated svg object, although I am not sure yet. One example is at https://jsfiddle.net/gs4v6k6d/157/.

- [x] add highlighting zones where user would insert notes

- [x] add click events to highlighting zones

- [x] add a specific note to a highlighting zone

- [ ] render a note outside a staff (?) may need this to display all possible notes the user will select and add to the staff 

- [x] render music sheet not elements independently for render speed. 
   >render speed, in the sense that we probably don't want to re-render the whole system for every new note. I think this can be answered by seeing if the staff itself can be hidden, either in code or in CSS. If so, each layer could have its own rendering, keeping things a bit more React

### CODE REVIEW

**Comment by caiokf** [comment]
For rendering, yes, we can draw each note independently, I imagine it may be a bit tricky to remove and add new notes upon state change, but we may have better luck with rendering of entire layers.

**Comment by caiokf** [comment]
now able to highlight note in an specific position. highlighting follows cursor and shows where note would be inserted. for now, the hover area of the note works well in the sense it is easy to position the notes and no interference on the overlap of noteheads, but we still need to increase the surface area of the hover a bit, which should be easy so i won't add this to the spike
screen shot 2017-04-27 at 9 56 21 am

**Comment by caiokf** [comment]
Performance-wise, i did some tests, and to render the staff, a couple of layers of notes and all the students option notes that would be available to be highlighted (for around 10 quarters) it took 200ms. Adding a few more quarters adds not much time, maybe 10ms each. I think it is acceptable. What do you think @rplotkin ?

**Comment by caiokf** [comment]
I also spiked the possibility to remove layers (student options that would be highlighted) and it is very easy. This would be useful for when the user selects something else on the toolbox, and we need to redraw the options with the correct note glyph and accidentals.

**Comment by rplotkin** [comment]
That is well within the threshold of allowable UX. Given your spike's success, let's flip this over into actual project code.

**Pull request closed without merging**
